[package]
name = "steam2record"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
config = "0.12"
